# 06 — Temperature sweep (−40 °C … +125 °C)

Passives scale with TCR. Typical $V_{\mathrm{ADJ}}(T)$ follows G05. Envelope WC at each T uses the **25 °C Electrical Characteristics box** at 25 °C and the **over-temperature box** everywhere else.

## Setup — editable BOM and run knobs

This cell is shared by every notebook. It puts `P5V_Regulator/` on `sys.path`
and builds **one** `CircuitParams` object. Change a resistor, capacitor, or
tolerance here and re-run: analytical, SPICE, WC, and MC all follow this object.

**Plot callouts:** each figure cell has an `ann = [dict(...), ...]` list.
Edit `text`, `xy` (data coords of the arrow tip), and `offset=(dx, dy)` in
**points** to nudge a label. Use `xytext=(x, y)` instead of `offset` for data
coordinates. `arrow=False` for a plain label. `ann = []` hides all callouts.

Tolerances are **fractions** (0.01 = 1 %). Figures go to `results/figures/`.

In [1]:
from pathlib import Path
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def _find_project_root() -> Path:
    start = Path.cwd().resolve()
    named = Path("Sections/Electronics/Analog_and_Digital/LT3010_5V_Supply")
    candidates = [start, *start.parents, start / named]
    if start.name == "notebooks":
        candidates.insert(0, start.parent)
    for cand in candidates:
        if (cand / "p5v_design" / "__init__.py").is_file():
            return cand
    return start

ROOT = _find_project_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from p5v_design.params import CircuitParams, ToleranceSpec, format_eng, LdoParams
from p5v_design import analysis, schematic, plots, stability
from p5v_design import plots_wc_mc as pwc
from p5v_design.ldo_model import dropout_v, ignd_a, tj_c, psrr_db, vadj_typical_vs_temp
from dataclasses import replace

# --- EDITABLE BOM ---
# Datasheet TA01, "5V Supply with Shutdown" (LT3010/LT3010-5 Rev. J page 1).
# Fixed 5 V part: SENSE tied to OUT (R1 = 0). No external divider (R2 open).
# Capacitors are the 1 µF parts drawn on that figure. Load is the labeled 50 mA.
# VIN is printed as 5.4 V to 80 V; 12 V is the single-point bias inside that range.
R1 = 0.0             # SENSE shorted to OUT
R2 = 1.0e12          # open — no bottom resistor
CFF = 0.0            # no feedforward capacitor on the fixed part
COUT = 1.0e-6
CIN = 1.0e-6
ESR_OUT = 10e-3      # ceramic assumption, not printed on TA01
ESR_IN = 10e-3
RLOAD = 100.0        # 5 V / 50 mA
R_TOL = 0.01         # 1 %
C_TOL = 0.10         # 10 %
VIN_NOM = 12.0
VIN_MIN = 5.4
VIN_MAX = 80.0
ILOAD_OP = 50e-3
N_MC = 2000
N_SPICE_MC = 40
N_LTSPICE_MC = 200
SKIP_SPICE_WC_MC = False
RUN_LTSPICE_BATCH = False
SPICE_WORKERS = None
LTSPICE_WORKERS = None

p = CircuitParams(
    r1=R1, r2=R2, cff=CFF, cout=COUT, cin=CIN,
    esr_out=ESR_OUT, esr_in=ESR_IN, r_load=RLOAD,
    r_tol=ToleranceSpec(R_TOL), c_tol=ToleranceSpec(C_TOL),
)
p = replace(p, op=replace(p.op, vin_nom=VIN_NOM, vin_min=VIN_MIN, vin_max=VIN_MAX,
                           iload_op=ILOAD_OP, r_load=RLOAD))

FIG = ROOT / "results" / "figures"
FIG.mkdir(parents=True, exist_ok=True)
print("gain =", p.gain, "  Vout nom =", analysis.vout_dc(p))
print("SPICE_WORKERS =", SPICE_WORKERS, "  N_MC =", N_MC)

gain = 1.0   Vout nom = 5.0
SPICE_WORKERS = None   N_MC = 2000

## What this cell plots

Seven figures from one analytical sweep `sweep_analytical(p)` on the MP grid
(−40 °C … +125 °C, 20 °C steps plus the usual corners −40 / 0 / 25 / 85 / 125).

| Figure | File | What it is |
|--------|------|------------|
| $V_{\mathrm{OUT}}$ vs $T$ | `06_vout_vs_t.png` | typical setpoint (black) + WC envelope (red band) |
| Dropout vs $T$ | `06_vdo_vs_t.png` | typ $V_{\mathrm{DO}}(T)$ vs datasheet max-over-temp |
| Temperature family | `06_temp_grid.png` | $V_{\mathrm{OUT}}$, $V_{\mathrm{ADJ}}$, $V_{\mathrm{DO}}$, $I_{\mathrm{GND}}$, $\eta$, $T_j$ |
| $I_{\mathrm{GND}}$ vs $T$ | `06_ignd_vs_t.png` | typ vs max GND-pin current |
| $P_{\mathrm{diss}}$ vs $T$ | `06_pdiss_vs_t.png` | $I_{\mathrm{LOAD}}(V_{\mathrm{IN}}-V_{\mathrm{OUT}})+I_{\mathrm{GND}}V_{\mathrm{IN}}$ |
| $T_j$ vs $T_A$ | `06_tj_vs_t.png` | $T_A + P_{\mathrm{tot}}\theta_{JA}$ vs 125 °C limit |
| PSRR | `06_psrr_vs_t.png` | G21 typ vs min (typ − 10 dB over-temp class) |

### Black line — typical $V_{\mathrm{OUT}}(T)$

At each grid temperature:

1. Scale $R_1$ and $R_2$ from 25 °C with the same TCR (default 100 ppm/°C).
   Same-sign TCR on both resistors leaves $R_1/R_2$ almost unchanged; the
   leftover is only the $\pm 1\,\%$ tolerance, not the TCR itself.
2. Replace $V_{\mathrm{ADJ}}$ with the **typical** G05 curve
   `vadj_typical_vs_temp(T)` (a few millivolts of bow).
3. Evaluate
   $V_{\mathrm{OUT}}=V_{\mathrm{ADJ}}(1+R_1/R_2)+I_{\mathrm{ADJ}}R_1$
   with typical $I_{\mathrm{ADJ}}=50\,\mathrm{nA}$.

That is why the black trace is a gentle arch, ~4.92 V at the cold and hot
ends. The fixed 5 V part is 5.000 V typical at 25 °C.

### Red band — worst-case envelope, and the notch at 25 °C

The band is **not** a Monte Carlo cloud and it is **not** a continuous
temperature coefficient of the LT3010 spec. It is the datasheet
**hypercube** of $V_{\mathrm{ADJ}}$, $I_{\mathrm{ADJ}}$, $R_1$, $R_2$
evaluated at each $T$:


$$
V_{\min}=V_{\mathrm{ADJ,lo}}\,(1+R_{1,\mathrm{lo}}/R_{2,\mathrm{hi}})
\qquad
V_{\max}=V_{\mathrm{ADJ,hi}}\,(1+R_{1,\mathrm{hi}}/R_{2,\mathrm{lo}})+I_{\mathrm{ADJ,hi}}R_{1,\mathrm{hi}}
$$


**Which $V_{\mathrm{ADJ}}$ box** is a datasheet switch, not a physical dip:

| Condition | Code | $V_{\mathrm{ADJ}}$ box (Rev. J p. 3) |
|-----------|------|--------------------------------------|
| $\lvert T-25\,^\circ\mathrm{C}\rvert\le 1\,^\circ\mathrm{C}$ | `over_temp=False` | **1.258 … 1.292 V** (25 °C) |
| everywhere else on the MP range | `over_temp=True` | **1.237 … 1.313 V** (over temp) |

The over-temp ADJ limits **already include line, load, and temperature**
(Notes 2, 3, 10). This plot does **not** stack extra line/load on top of
that box (`error_mode='envelope'`).

The V-shaped notch is therefore:

- At **5 °C** and **45 °C** (20 °C grid neighbors of 25 °C) the code still
  uses the **wide** over-temp box → band ≈ 4.731 … 5.175 V.
- At the single grid point **25 °C** it uses the **tighter** 25 °C box →
  band ≈ 4.812 … 5.091 V.
- Matplotlib draws **straight lines** between those three points, so you
  see a notch rather than a step. It is an artifact of a discrete spec
  table + linear interpolation, not a real 25 °C “suck-in” of the silicon.

$I_{\mathrm{ADJ,hi}}$ also grows above ~100 °C (G15), which slightly
widens the hot end of the upper bound; TCR on $R_1,R_2$ is a much smaller
effect because both resistors move together.

### How to read it

- The **green dotted line** is the 5.000 V goal. Typical (black) sits
  the page-3 typical output, 5.000 V, at every $T$ before the temperature bow.
- If the red band at 25 °C is the production screen, the over-temp band
  is the guarantee the customer sees across −55 … +125 °C.
- Dropout, $I_{\mathrm{GND}}$, $P_{\mathrm{diss}}$, and $T_j$ in the
  later axes of this cell do **not** use that ADJ box switch — they use
  the datasheet typ vs max-over-temp columns vs load/temperature.

In [2]:
from p5v_design.temperature import sweep_analytical
sw = sweep_analytical(p)
sw.save(ROOT/"results"/"temp_analytical.csv")
display(sw.frame.head())
ann = [
    dict(text="25 °C", xy=(25, float(sw.frame.loc[sw.frame.temp_c==25, "vout"].iloc[0])),
         offset=(12, 10), arrow=True),
    dict(text="E min −40 °C", xy=(-40, float(sw.frame.iloc[0]["vout"])), offset=(12, -12), arrow=True),
]
plots.plot_temp_sweep(
    sw.frame.temp_c.to_numpy(), sw.frame.vout.to_numpy(),
    vout_lo=sw.frame.vout_wc_lo.to_numpy(), vout_hi=sw.frame.vout_wc_hi.to_numpy(),
    annotations=ann, path=FIG/"06_vout_vs_t.png",
)
plt.show()

,temp_c,vadj_typ,r1,r2,vout,vout_wc_lo,vout_wc_hi,vdo_typ,vdo_wc,ignd_typ,ignd_max,p_diss,tj_c,efficiency
0,-40.0,4.976872,0.0,9.935000e+11,4.976872,4.850,5.150,0.209,0.55,0.0018,0.0033,0.372756,-25.089744,0.400328
1,-20.0,4.988632,0.0,9.955000e+11,4.988632,4.850,5.150,0.237,0.55,0.0018,0.0033,0.372168,-5.113264,0.401273
2,0.0,4.998040,0.0,9.975000e+11,4.998040,4.850,5.150,0.265,0.55,0.0018,0.0033,0.371698,14.867920,0.402030
3,20.0,4.999608,0.0,9.995000e+11,4.999608,4.850,5.150,0.293,0.55,0.0018,0.0033,0.371620,34.864784,0.402156
4,25.0,5.000000,0.0,1.000000e+12,5.000000,4.925,5.075,0.300,0.55,0.0018,0.0033,0.371600,39.864000,0.402188

cell:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## ngspice and LTspice WC vs temperature

Same ADJ-box switch as the analytical band (25 °C box only at 25 °C).

| Engine | Typical | WC |
|--------|---------|----|
| ngspice behavioral | OP on the **full** $T$ grid, G05 $V_{\mathrm{ADJ}}(T)$ | 16 corners at each $T$ |
| LTspice vendor lib | unbroken ADJ, macromodel $V_{\mathrm{ADJ}}(T)$ | 16 injected corners at **−40 / 25 / 125 °C** only |

LTspice WC is drawn as **error bars**, not a filled band, so three temperatures
do not invent a notch by interpolation. Set `SKIP_SPICE_WC_MC = True` to skip
ngspice; set `RUN_LTSPICE_BATCH = True` (or pre-run
`python LTSpice/run_ltspice_batch.py temp`) for vendor-lib logs.

The vendor macromodel is **typical-only** and is not guaranteed at MP cold.
Expect LTspice typical/WC at −55 °C to sit well below the datasheet envelope
(the lib’s ADJ voltage collapses); 25 °C and 125 °C should track analytical
with the same slight low bias already seen in notebook 05.

In [3]:
from p5v_design.temperature import (
    sweep_ngspice_nominal, sweep_ngspice_wc, sweep_ltspice_from_logs, temp_tag,
)
from p5v_design.simulate import find_ngspice

T_LTSPICE = [-40.0, 25.0, 125.0]
ng_nom = ng_wc = None
lt_nom = lt_wc = None

HAVE_SPICE = False
try:
    find_ngspice()
    HAVE_SPICE = True
except FileNotFoundError as e:
    print(e)

if HAVE_SPICE and not SKIP_SPICE_WC_MC:
    ng_nom = sweep_ngspice_nominal(
        p, workdir=ROOT/"results"/"ngspice_temp", root=ROOT,
    )
    ng_wc = sweep_ngspice_wc(
        p, workdir=ROOT/"results"/"ngspice_wc_temp", root=ROOT,
        max_workers=SPICE_WORKERS,
    )
    ng_nom.to_csv(ROOT/"results"/"temp_ngspice_nom.csv", index=False)
    ng_wc.to_csv(ROOT/"results"/"temp_ngspice_wc.csv", index=False)
    display(ng_wc)
else:
    print("ngspice temperature WC skipped")

import importlib.util
lt_py = ROOT / "LTSpice" / "run_ltspice_batch.py"
if lt_py.is_file():
    spec = importlib.util.spec_from_file_location("run_ltspice_batch", lt_py)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.write_temp_decks(p, temps=T_LTSPICE)
else:
    print("LTspice helper is not in this repository. Vendor LT3010.lib is not redistributed.")
if RUN_LTSPICE_BATCH:
    from p5v_design.ltspice_io import find_ltspice, run_ltspice_decks
    try:
        find_ltspice()
        decks = []
        for T in T_LTSPICE:
            d = ROOT/"LTSpice"/"Temp"/temp_tag(T)
            decks += [d/"P5V_ISO_Regulator_op.cir", d/"P5V_ISO_Regulator_WC.cir"]
        run_ltspice_decks(decks, max_workers=LTSPICE_WORKERS)
    except FileNotFoundError as e:
        print(e)
else:
    print("LTspice temp batch skipped (RUN_LTSPICE_BATCH=False). Existing logs still parsed.")

lt_nom, lt_wc = sweep_ltspice_from_logs(p, temp_root=ROOT/"LTSpice"/"Temp", temps=T_LTSPICE)
display(lt_nom)
display(lt_wc)

kw = dict(
    vout_lo=sw.frame.vout_wc_lo.to_numpy(), vout_hi=sw.frame.vout_wc_hi.to_numpy(),
)
if ng_nom is not None:
    kw["ng_temps"] = ng_nom.temp_c.to_numpy()
    kw["ng_vout"] = ng_nom.vout.to_numpy()
if ng_wc is not None:
    kw["ng_lo"] = ng_wc.vout_lo.to_numpy()
    kw["ng_hi"] = ng_wc.vout_hi.to_numpy()
if lt_nom is not None and lt_nom.vout.notna().any():
    kw["lt_temps"] = lt_nom.temp_c.to_numpy()
    kw["lt_vout"] = lt_nom.vout.to_numpy()
if lt_wc is not None and lt_wc.vout_lo.notna().any():
    kw["lt_lo"] = lt_wc.vout_lo.to_numpy()
    kw["lt_hi"] = lt_wc.vout_hi.to_numpy()
ann_ov = [
    dict(text="25 °C box (notch)", xy=(25.0, float(sw.frame.loc[np.isclose(sw.frame.temp_c, 25), "vout_wc_hi"].iloc[0])),
         offset=(14, 12), arrow=True, color="C3"),
    dict(text="5.000 V", xy=(80.0, 5.0), offset=(8, 10), arrow=True, color="#2ca02c"),
]
plots.plot_temp_sweep(
    sw.frame.temp_c.to_numpy(), sw.frame.vout.to_numpy(),
    annotations=ann_ov, path=FIG/"06_vout_vs_t_engines.png",
    title=r"$V_{\mathrm{OUT}}$ vs $T$  analytical / ngspice / LTspice",
    **kw,
)
plt.show()

# Three-temperature comparison table
rows = []
for T in T_LTSPICE:
    an = sw.frame.loc[np.isclose(sw.frame.temp_c, T)].iloc[0]
    rec = {"T_C": T, "an_nom": an.vout, "an_lo": an.vout_wc_lo, "an_hi": an.vout_wc_hi}
    if ng_nom is not None:
        rec["ng_nom"] = float(ng_nom.loc[np.isclose(ng_nom.temp_c, T), "vout"].iloc[0])
    if ng_wc is not None:
        rec["ng_lo"] = float(ng_wc.loc[np.isclose(ng_wc.temp_c, T), "vout_lo"].iloc[0])
        rec["ng_hi"] = float(ng_wc.loc[np.isclose(ng_wc.temp_c, T), "vout_hi"].iloc[0])
    if lt_nom is not None and lt_nom.vout.notna().any():
        rec["lt_nom"] = float(lt_nom.loc[np.isclose(lt_nom.temp_c, T), "vout"].iloc[0])
    if lt_wc is not None and lt_wc.vout_lo.notna().any():
        rec["lt_lo"] = float(lt_wc.loc[np.isclose(lt_wc.temp_c, T), "vout_lo"].iloc[0])
        rec["lt_hi"] = float(lt_wc.loc[np.isclose(lt_wc.temp_c, T), "vout_hi"].iloc[0])
    rows.append(rec)
cmp = pd.DataFrame(rows)
if "ng_nom" in cmp.columns:
    cmp["ng-an_mV"] = 1e3 * (cmp["ng_nom"] - cmp["an_nom"])
display(cmp)

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Valo_Iahi           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.00s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.01s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.02s  run R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Vahi_… 0.02s +3
  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.04s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Vahi_… 0.03s +4

  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.04s  run R1lo_R2lo_Valo_… 0.04s, R1lo_R2lo_Valo_… 0.04s, R1lo_R2lo_Vahi_… 0.04s +5
  →  start  R1hi_R2lo_Valo_Ialo           t+  0.11s  run R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Vahi_… 0.10s +5

  ✓    1/16  OK    R1lo_R2hi_Valo_Ialo           job   0.10s  wall   0.22s  ETA   3.35s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.24s  run R1lo_R2lo_Valo_… 0.24s, R1lo_R2lo_Vahi_… 0.24s, R1lo_R2lo_Vahi_… 0.23s +5

  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.33s  run R1lo_R2lo_Valo_… 0.33s, R1lo_R2lo_Vahi_… 0.32s, R1lo_R2lo_Vahi_… 0.32s +5
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.33s  run R1lo_R2lo_Valo_… 0.33s, R1lo_R2lo_Vahi_… 0.32s, R1lo_R2hi_Vahi_… 0.29s +5
  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.24s  wall   0.34s  ETA   2.36s  Vout=4.8500
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.35s  run R1lo_R2lo_Valo_… 0.35s, R1lo_R2hi_Vahi_… 0.31s, R1lo_R2hi_Vahi_… 0.30s +5

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.36s  run R1lo_R2lo_Valo_… 0.36s, R1lo_R2hi_Vahi_… 0.33s, R1hi_R2lo_Valo_… 0.25s +5
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.38s  run R1lo_R2lo_Valo_… 0.38s, R1hi_R2lo_Valo_… 0.27s, R1hi_R2lo_Valo_… 0.13s +5

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.48s  run R1hi_R2lo_Valo_… 0.37s, R1hi_R2lo_Valo_… 0.24s, R1hi_R2lo_Vahi_… 0.16s +5
  ✓    3/16  OK    R1lo_R2hi_Valo_Iahi           job   0.30s  wall   0.51s  ETA   2.19s  Vout=4.8500

  ✓    4/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.32s  wall   0.70s  ETA   2.11s  Vout=5.1499

  ✓    5/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.34s  wall   0.77s  ETA   1.69s  Vout=5.1499

  ✓    6/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.32s  wall   0.90s  ETA   1.50s  Vout=5.1499

  ✓    7/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.34s  wall   0.92s  ETA   1.19s  Vout=5.1499

  ✓    8/16  OK    R1lo_R2lo_Valo_Ialo           job   0.48s  wall   0.93s  ETA   0.93s  Vout=4.8500

  ✓    9/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.27s  wall   0.94s  ETA   0.73s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2lo_Valo_Ialo           job   0.52s  wall   0.95s  ETA   0.57s  Vout=4.8500

  ✓   11/16  OK    R1hi_R2hi_Valo_Ialo           job   0.35s  wall   0.96s  ETA   0.43s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.23s  wall   0.97s  ETA   0.32s  Vout=5.1499

  ✓   13/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.34s  wall   0.99s  ETA   0.23s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Valo_Iahi           job   0.48s  wall   0.99s  ETA   0.14s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.60s  wall   1.00s  ETA   0.07s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2lo_Valo_Iahi           job   0.69s  wall   1.00s  ETA   0.00s  Vout=4.8500

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.10s  cpu=5.92s  speedup=5.39× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Valo_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.04s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.07s  run R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.03s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.07s  run R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.04s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.08s  run R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.04s +3
  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.10s  run R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Vahi_… 0.06s +4
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.13s  run R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Vahi_… 0.09s +5

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.31s  run R1lo_R2lo_Valo_… 0.30s, R1lo_R2lo_Valo_… 0.30s, R1lo_R2lo_Vahi_… 0.28s +5

  ✓    1/16  OK    R1lo_R2hi_Valo_Ialo           job   0.24s  wall   0.47s  ETA   7.11s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.51s  run R1lo_R2lo_Valo_… 0.50s, R1lo_R2lo_Vahi_… 0.47s, R1lo_R2lo_Vahi_… 0.44s +5
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.53s  run R1lo_R2lo_Valo_… 0.52s, R1lo_R2lo_Vahi_… 0.49s, R1lo_R2lo_Vahi_… 0.46s +5
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.53s  run R1lo_R2lo_Valo_… 0.52s, R1lo_R2lo_Vahi_… 0.49s, R1lo_R2lo_Vahi_… 0.46s +5

  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.50s  wall   0.64s  ETA   4.46s  Vout=4.8500  →  start  R1hi_R2hi_Valo_Ialo           t+  0.67s  run R1lo_R2lo_Vahi_… 0.64s, R1lo_R2lo_Vahi_… 0.60s, R1lo_R2hi_Vahi_… 0.55s +5

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.81s  run R1lo_R2lo_Vahi_… 0.77s, R1lo_R2lo_Vahi_… 0.74s, R1lo_R2hi_Vahi_… 0.68s +5  ✓    3/16  OK    R1lo_R2hi_Valo_Iahi           job   0.45s  wall   0.83s  ETA   3.58s  Vout=4.8500
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.83s  run R1lo_R2lo_Vahi_… 0.79s, R1lo_R2lo_Vahi_… 0.76s, R1lo_R2hi_Vahi_… 0.70s +5
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.85s  run R1lo_R2lo_Vahi_… 0.81s, R1lo_R2hi_Vahi_… 0.72s, R1hi_R2lo_Vahi_… 0.32s +5

  ✓    4/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.43s  wall   0.92s  ETA   2.76s  Vout=5.1499

  ✓    5/16  OK    R1lo_R2lo_Valo_Ialo           job   0.66s  wall   0.94s  ETA   2.06s  Vout=4.8500

  ✓    6/16  OK    R1hi_R2lo_Valo_Iahi           job   0.30s  wall   1.01s  ETA   1.68s  Vout=4.8500

  ✓    7/16  OK    R1hi_R2lo_Valo_Ialo           job   0.52s  wall   1.02s  ETA   1.31s  Vout=4.8500

  …  7/16 done  ok=7 fail=0  wall 1.05s  ETA 1.35s  run R1hi_R2hi_Valo_… 0.24s, R1hi_R2hi_Vahi_… 0.22s
  ✓    8/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.77s  wall   1.06s  ETA   1.06s  Vout=5.1499

  ✓    9/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.72s  wall   1.09s  ETA   0.85s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.33s  wall   1.13s  ETA   0.68s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.38s  wall   1.15s  ETA   0.52s  Vout=5.1499

  ✓   12/16  OK    R1hi_R2hi_Valo_Ialo           job   0.31s  wall   1.15s  ETA   0.38s  Vout=4.8500

  ✓   13/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.95s  wall   1.16s  ETA   0.27s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.20s  wall   1.17s  ETA   0.17s  Vout=5.1499

  ✓   15/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.25s  wall   1.17s  ETA   0.08s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2hi_Valo_Iahi           job   0.29s  wall   1.17s  ETA   0.00s  Vout=4.8500

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.26s  cpu=7.32s  speedup=5.82× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.07s  run R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Vahi_… 0.07s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.10s  run R1lo_R2lo_Valo_… 0.10s, R1lo_R2lo_Valo_… 0.10s, R1lo_R2lo_Vahi_… 0.10s +2
  →  start  R1lo_R2hi_Valo_Iahi           t+  0.19s  run R1lo_R2lo_Valo_… 0.19s, R1lo_R2lo_Valo_… 0.18s, R1lo_R2lo_Vahi_… 0.11s +2
  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.21s  run R1lo_R2lo_Valo_… 0.21s, R1lo_R2lo_Valo_… 0.21s, R1lo_R2lo_Vahi_… 0.14s +3
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.23s  run R1lo_R2lo_Valo_… 0.22s, R1lo_R2lo_Vahi_… 0.15s, R1lo_R2hi_Valo_… 0.12s +3

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.23s  run R1lo_R2lo_Valo_… 0.23s, R1lo_R2lo_Vahi_… 0.16s, R1lo_R2hi_Valo_… 0.13s +4

  ✓    1/16  OK    R1lo_R2lo_Valo_Ialo           job   0.22s  wall   0.26s  ETA   3.92s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.30s  run R1lo_R2lo_Vahi_… 0.22s, R1lo_R2hi_Valo_… 0.19s, R1lo_R2hi_Valo_… 0.11s +4
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.30s  run R1lo_R2lo_Vahi_… 0.23s, R1lo_R2hi_Valo_… 0.20s, R1lo_R2hi_Valo_… 0.11s +5

  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.46s  run R1lo_R2lo_Vahi_… 0.39s, R1lo_R2hi_Valo_… 0.36s, R1lo_R2hi_Valo_… 0.28s +5
  ✓    2/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.18s  wall   0.52s  ETA   3.61s  Vout=5.1499
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.55s  run R1lo_R2lo_Vahi_… 0.48s, R1lo_R2hi_Valo_… 0.45s, R1lo_R2hi_Valo_… 0.37s +5
  →  start  R1hi_R2hi_Valo_Iahi           t+  0.58s  run R1lo_R2lo_Vahi_… 0.50s, R1lo_R2hi_Valo_… 0.39s, R1lo_R2hi_Vahi_… 0.36s +5

  ✓    3/16  OK    R1lo_R2lo_Valo_Iahi           job   0.29s  wall   0.62s  ETA   2.67s  Vout=4.8500

  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.78s  run R1lo_R2lo_Vahi_… 0.70s, R1lo_R2hi_Valo_… 0.59s, R1hi_R2lo_Valo_… 0.48s +5

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.83s  run R1lo_R2lo_Vahi_… 0.75s, R1hi_R2lo_Valo_… 0.53s, R1hi_R2lo_Vahi_… 0.53s +5

  ✓    4/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.24s  wall   0.92s  ETA   2.77s  Vout=5.1499

  ✓    5/16  OK    R1hi_R2lo_Valo_Ialo           job   0.32s  wall   0.93s  ETA   2.05s  Vout=4.8500

  ✓    6/16  OK    R1lo_R2hi_Valo_Ialo           job   0.47s  wall   0.94s  ETA   1.57s  Vout=4.8500

  ✓    7/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.56s  wall   0.94s  ETA   1.21s  Vout=5.1499

  ✓    8/16  OK    R1lo_R2hi_Valo_Iahi           job   0.64s  wall   0.98s  ETA   0.98s  Vout=4.8500

  …  8/16 done  ok=8 fail=0  wall 1.02s  ETA 1.02s  run R1hi_R2lo_Vahi_… 0.56s, R1hi_R2hi_Valo_… 0.47s, R1hi_R2hi_Valo_… 0.45s +2
  ✓    9/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.79s  wall   1.05s  ETA   0.82s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.63s  wall   1.06s  ETA   0.64s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2lo_Valo_Iahi           job   0.66s  wall   1.09s  ETA   0.49s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2hi_Valo_Ialo           job   0.50s  wall   1.10s  ETA   0.37s  Vout=4.8500

  ✓   13/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.63s  wall   1.14s  ETA   0.26s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Valo_Iahi           job   0.52s  wall   1.14s  ETA   0.16s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.36s  wall   1.15s  ETA   0.08s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.31s  wall   1.18s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.19s  cpu=7.32s  speedup=6.14× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.02s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.00s +1

  →  start  R1lo_R2hi_Valo_Ialo           t+  0.09s  run R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Vahi_… 0.07s +2
  →  start  R1lo_R2hi_Valo_Iahi           t+  0.09s  run R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Vahi_… 0.08s +3

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.13s  run R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Vahi_… 0.12s +4  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.26s  run R1lo_R2lo_Valo_… 0.25s, R1lo_R2lo_Valo_… 0.25s, R1lo_R2lo_Vahi_… 0.24s +5

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.34s  run R1lo_R2lo_Vahi_… 0.33s, R1lo_R2lo_Vahi_… 0.33s, R1lo_R2hi_Valo_… 0.26s +4
  ✓    1/16  OK    R1lo_R2lo_Valo_Ialo           job   0.29s  wall   0.36s  ETA   5.36s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.37s  run R1lo_R2lo_Vahi_… 0.35s, R1lo_R2hi_Valo_… 0.28s, R1lo_R2hi_Valo_… 0.28s +4
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.37s  run R1lo_R2lo_Vahi_… 0.35s, R1lo_R2hi_Valo_… 0.28s, R1lo_R2hi_Valo_… 0.28s +5

  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.41s  run R1lo_R2hi_Valo_… 0.32s, R1lo_R2hi_Valo_… 0.32s, R1lo_R2hi_Vahi_… 0.28s +5

  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.30s  wall   0.47s  ETA   3.30s  Vout=4.8500

  →  start  R1hi_R2hi_Valo_Ialo           t+  0.49s  run R1lo_R2hi_Valo_… 0.41s, R1lo_R2hi_Vahi_… 0.36s, R1lo_R2hi_Vahi_… 0.24s +5

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.59s  run R1lo_R2hi_Vahi_… 0.45s, R1lo_R2hi_Vahi_… 0.33s, R1hi_R2lo_Valo_… 0.24s +5

  ✓    3/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.35s  wall   0.69s  ETA   3.00s  Vout=5.1499

  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.73s  run R1lo_R2hi_Vahi_… 0.60s, R1hi_R2lo_Valo_… 0.39s, R1hi_R2lo_Valo_… 0.37s +5
  ✓    4/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.40s  wall   0.74s  ETA   2.23s  Vout=5.1499
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.75s  run R1hi_R2lo_Valo_… 0.41s, R1hi_R2lo_Valo_… 0.38s, R1hi_R2lo_Vahi_… 0.38s +5

  ✓    5/16  OK    R1lo_R2hi_Valo_Iahi           job   0.40s  wall   0.82s  ETA   1.80s  Vout=4.8500

  ✓    6/16  OK    R1lo_R2hi_Valo_Ialo           job   0.50s  wall   0.83s  ETA   1.39s  Vout=4.8500

  ✓    7/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.48s  wall   0.90s  ETA   1.16s  Vout=5.1499

  ✓    8/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.62s  wall   0.91s  ETA   0.91s  Vout=5.1499

  ✓    9/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.36s  wall   0.92s  ETA   0.71s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2lo_Valo_Iahi           job   0.43s  wall   0.92s  ETA   0.55s  Vout=4.8500

  ✓   11/16  OK    R1hi_R2hi_Valo_Ialo           job   0.31s  wall   0.92s  ETA   0.42s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.44s  wall   0.92s  ETA   0.31s  Vout=5.1499

  ✓   13/16  OK    R1hi_R2hi_Valo_Iahi           job   0.29s  wall   0.93s  ETA   0.21s  Vout=4.8500

  ✓   14/16  OK    R1hi_R2lo_Valo_Ialo           job   0.54s  wall   0.94s  ETA   0.13s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.19s  wall   0.95s  ETA   0.06s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.23s  wall   0.98s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.05s  cpu=6.12s  speedup=5.85× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Valo_Iahi           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.03s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Vahi_… 0.00s
  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.05s  run R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Valo_… 0.04s, R1lo_R2lo_Vahi_… 0.02s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.05s  run R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Valo_… 0.04s, R1lo_R2lo_Vahi_… 0.02s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.13s  run R1lo_R2lo_Valo_… 0.12s, R1lo_R2lo_Vahi_… 0.09s, R1lo_R2lo_Vahi_… 0.08s +2

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.18s  run R1lo_R2lo_Vahi_… 0.15s, R1lo_R2lo_Vahi_… 0.13s, R1lo_R2hi_Valo_… 0.13s +2
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.22s  run R1lo_R2lo_Vahi_… 0.19s, R1lo_R2lo_Vahi_… 0.17s, R1lo_R2hi_Valo_… 0.17s +3
  →  start  R1hi_R2lo_Valo_Ialo           t+  0.23s  run R1lo_R2lo_Vahi_… 0.20s, R1lo_R2lo_Vahi_… 0.18s, R1lo_R2hi_Valo_… 0.18s +4
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.24s  run R1lo_R2lo_Vahi_… 0.21s, R1lo_R2lo_Vahi_… 0.19s, R1lo_R2hi_Valo_… 0.19s +5
  ✓    1/16  OK    R1lo_R2lo_Valo_Iahi           job   0.12s  wall   0.24s  ETA   3.67s  Vout=4.9250

  ✓    2/16  OK    R1lo_R2lo_Valo_Ialo           job   0.17s  wall   0.28s  ETA   1.97s  Vout=4.9250
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.33s  run R1lo_R2lo_Vahi_… 0.30s, R1lo_R2hi_Valo_… 0.29s, R1lo_R2hi_Valo_… 0.21s +5
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.46s  run R1lo_R2lo_Vahi_… 0.43s, R1lo_R2hi_Valo_… 0.33s, R1lo_R2hi_Vahi_… 0.28s +5
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.48s  run R1lo_R2lo_Vahi_… 0.45s, R1lo_R2hi_Valo_… 0.35s, R1lo_R2hi_Vahi_… 0.30s +5

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.49s  run R1lo_R2hi_Valo_… 0.37s, R1lo_R2hi_Vahi_… 0.31s, R1lo_R2hi_Vahi_… 0.27s +5

  ✓    3/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.29s  wall   0.51s  ETA   2.20s  Vout=5.0749
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.55s  run R1lo_R2hi_Valo_… 0.42s, R1lo_R2hi_Vahi_… 0.37s, R1hi_R2lo_Valo_… 0.31s +5

  ✓    4/16  OK    R1lo_R2hi_Valo_Ialo           job   0.41s  wall   0.74s  ETA   2.21s  Vout=4.9250
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.63s  run R1lo_R2hi_Valo_… 0.50s, R1lo_R2hi_Vahi_… 0.45s, R1hi_R2lo_Vahi_… 0.29s +5

  ✓    5/16  OK    R1hi_R2lo_Valo_Ialo           job   0.25s  wall   0.83s  ETA   1.82s  Vout=4.9250

  ✓    6/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.46s  wall   0.83s  ETA   1.39s  Vout=5.0749

  ✓    7/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.33s  wall   0.93s  ETA   1.20s  Vout=5.0749

  ✓    8/16  OK    R1hi_R2lo_Valo_Iahi           job   0.39s  wall   0.99s  ETA   0.99s  Vout=4.9250

  ✓    9/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.55s  wall   1.05s  ETA   0.82s  Vout=5.0749

  ✓   10/16  OK    R1lo_R2hi_Valo_Iahi           job   0.62s  wall   1.05s  ETA   0.63s  Vout=4.9250

  ✓   11/16  OK    R1hi_R2hi_Valo_Iahi           job   0.44s  wall   1.05s  ETA   0.48s  Vout=4.9250

  ✓   12/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.60s  wall   1.05s  ETA   0.35s  Vout=5.0749

  ✓   13/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.40s  wall   1.06s  ETA   0.24s  Vout=5.0749

  ✓   14/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.58s  wall   1.07s  ETA   0.15s  Vout=5.0749

  ✓   15/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.49s  wall   1.09s  ETA   0.07s  Vout=5.0749

  ✓   16/16  OK    R1hi_R2hi_Valo_Ialo           job   0.57s  wall   1.10s  ETA   0.00s  Vout=4.9250

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.22s  cpu=6.68s  speedup=5.48× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.03s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.06s  run R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Valo_… 0.04s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.15s  run R1lo_R2lo_Valo_… 0.14s, R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Vahi_… 0.09s +1

  →  start  R1lo_R2hi_Valo_Ialo           t+  0.22s  run R1lo_R2lo_Valo_… 0.20s, R1lo_R2lo_Valo_… 0.19s, R1lo_R2lo_Vahi_… 0.16s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.26s  run R1lo_R2lo_Valo_… 0.24s, R1lo_R2lo_Vahi_… 0.20s, R1lo_R2lo_Vahi_… 0.11s +2

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.30s  run R1lo_R2lo_Valo_… 0.28s, R1lo_R2lo_Vahi_… 0.24s, R1lo_R2lo_Vahi_… 0.15s +3

  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.34s  run R1lo_R2lo_Valo_… 0.31s, R1lo_R2lo_Vahi_… 0.28s, R1lo_R2lo_Vahi_… 0.19s +4

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.46s  run R1lo_R2lo_Valo_… 0.43s, R1lo_R2lo_Vahi_… 0.30s, R1lo_R2hi_Valo_… 0.24s +4

  →  start  R1hi_R2lo_Valo_Iahi           t+  0.50s  run R1lo_R2lo_Vahi_… 0.35s, R1lo_R2hi_Valo_… 0.28s, R1lo_R2hi_Valo_… 0.24s +4

  ✓    1/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.36s  wall   0.57s  ETA   8.48s  Vout=5.1499
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.57s  run R1lo_R2hi_Valo_… 0.35s, R1lo_R2hi_Valo_… 0.31s, R1lo_R2hi_Vahi_… 0.23s +3

  ✓    2/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.22s  wall   0.59s  ETA   4.15s  Vout=5.1499  →  start  R1hi_R2hi_Valo_Ialo           t+  0.64s  run R1lo_R2hi_Valo_… 0.42s, R1lo_R2hi_Valo_… 0.38s, R1lo_R2hi_Vahi_… 0.30s +4

  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.67s  run R1lo_R2hi_Valo_… 0.45s, R1lo_R2hi_Valo_… 0.40s, R1lo_R2hi_Vahi_… 0.33s +5

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.73s  run R1lo_R2hi_Valo_… 0.51s, R1lo_R2hi_Vahi_… 0.39s, R1hi_R2lo_Valo_… 0.28s +5
  ✓    3/16  OK    R1lo_R2lo_Valo_Iahi           job   0.47s  wall   0.75s  ETA   3.23s  Vout=4.8500

  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.87s  run R1lo_R2hi_Valo_… 0.65s, R1lo_R2hi_Vahi_… 0.53s, R1hi_R2lo_Valo_… 0.41s +5
  ✓    4/16  OK    R1lo_R2lo_Valo_Ialo           job   0.24s  wall   0.89s  ETA   2.67s  Vout=4.8500

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.94s  run R1lo_R2hi_Valo_… 0.72s, R1hi_R2lo_Valo_… 0.49s, R1hi_R2lo_Vahi_… 0.37s +5
  …  4/16 done  ok=4 fail=0  wall 1.01s  ETA 3.02s  run R1hi_R2lo_Valo_… 0.55s, R1hi_R2hi_Valo_… 0.37s, R1hi_R2lo_Vahi_… 0.34s +3

  ✓    5/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.36s  wall   1.05s  ETA   2.32s  Vout=5.1499

  ✓    6/16  OK    R1lo_R2hi_Valo_Iahi           job   0.47s  wall   1.14s  ETA   1.91s  Vout=4.8500

  ✓    7/16  OK    R1hi_R2lo_Valo_Iahi           job   0.37s  wall   1.26s  ETA   1.62s  Vout=4.8500

  ✓    8/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.60s  wall   1.29s  ETA   1.29s  Vout=5.1499

  ✓    9/16  OK    R1lo_R2hi_Valo_Ialo           job   0.76s  wall   1.30s  ETA   1.01s  Vout=4.8500

  ✓   10/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.44s  wall   1.32s  ETA   0.79s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.37s  wall   1.33s  ETA   0.61s  Vout=5.1499

  ✓   12/16  OK    R1hi_R2hi_Valo_Ialo           job   0.54s  wall   1.38s  ETA   0.46s  Vout=4.8500

  ✓   13/16  OK    R1hi_R2lo_Valo_Ialo           job   0.81s  wall   1.40s  ETA   0.32s  Vout=4.8500

  ✓   14/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.39s  wall   1.43s  ETA   0.20s  Vout=5.1499

  ✓   15/16  OK    R1hi_R2hi_Valo_Iahi           job   0.68s  wall   1.43s  ETA   0.10s  Vout=4.8500

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.48s  wall   1.44s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.51s  cpu=7.56s  speedup=4.99× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.02s  run R1lo_R2lo_Valo_… 0.00s  →  start  R1lo_R2lo_Valo_Iahi           t+  0.03s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.03s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.09s  run R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.06s +1  →  start  R1lo_R2hi_Valo_Ialo           t+  0.11s  run R1lo_R2lo_Valo_… 0.10s, R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Vahi_… 0.09s +2
  →  start  R1lo_R2hi_Valo_Iahi           t+  0.18s  run R1lo_R2lo_Valo_… 0.16s, R1lo_R2lo_Valo_… 0.15s, R1lo_R2lo_Vahi_… 0.15s +3
  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.22s  run R1lo_R2lo_Valo_… 0.20s, R1lo_R2lo_Valo_… 0.19s, R1lo_R2lo_Vahi_… 0.19s +4

  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.35s  run R1lo_R2lo_Valo_… 0.33s, R1lo_R2lo_Valo_… 0.33s, R1lo_R2lo_Vahi_… 0.32s +5  →  start  R1hi_R2lo_Valo_Ialo           t+  0.40s  run R1lo_R2lo_Valo_… 0.38s, R1lo_R2lo_Valo_… 0.37s, R1lo_R2lo_Vahi_… 0.37s +5
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.42s  run R1lo_R2lo_Valo_… 0.40s, R1lo_R2lo_Valo_… 0.39s, R1lo_R2lo_Vahi_… 0.39s +5

  ✓    1/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.31s  wall   0.45s  ETA   6.72s  Vout=5.1499

  ✓    2/16  OK    R1lo_R2hi_Valo_Ialo           job   0.31s  wall   0.49s  ETA   3.45s  Vout=4.8500

  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.60s  run R1lo_R2lo_Valo_… 0.58s, R1lo_R2lo_Valo_… 0.57s, R1lo_R2lo_Vahi_… 0.57s +5  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.61s  run R1lo_R2lo_Valo_… 0.59s, R1lo_R2lo_Vahi_… 0.58s, R1lo_R2hi_Vahi_… 0.39s +5
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.63s  run R1lo_R2lo_Vahi_… 0.60s, R1lo_R2hi_Vahi_… 0.41s, R1lo_R2hi_Vahi_… 0.28s +5  →  start  R1hi_R2hi_Valo_Iahi           t+  0.66s  run R1lo_R2lo_Vahi_… 0.63s, R1lo_R2hi_Vahi_… 0.30s, R1hi_R2lo_Valo_… 0.26s +5

  ✓    3/16  OK    R1lo_R2hi_Valo_Iahi           job   0.42s  wall   0.68s  ETA   2.93s  Vout=4.8500
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.69s  run R1lo_R2hi_Vahi_… 0.34s, R1hi_R2lo_Valo_… 0.29s, R1hi_R2lo_Valo_… 0.28s +5

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.84s  run R1lo_R2hi_Vahi_… 0.49s, R1hi_R2lo_Valo_… 0.42s, R1hi_R2lo_Vahi_… 0.24s +5

  ✓    4/16  OK    R1lo_R2lo_Valo_Iahi           job   0.58s  wall   0.92s  ETA   2.76s  Vout=4.8500

  …  4/16 done  ok=4 fail=0  wall 1.07s  ETA 3.20s  run R1hi_R2lo_Valo_… 0.65s, R1hi_R2lo_Vahi_… 0.47s, R1hi_R2hi_Valo_… 0.44s +3

  ✓    5/16  OK    R1lo_R2lo_Valo_Ialo           job   0.61s  wall   1.17s  ETA   2.58s  Vout=4.8500

  ✓    6/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.44s  wall   1.22s  ETA   2.03s  Vout=5.1499

  ✓    7/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.66s  wall   1.33s  ETA   1.71s  Vout=5.1499

  ✓    8/16  OK    R1hi_R2lo_Valo_Ialo           job   0.44s  wall   1.35s  ETA   1.35s  Vout=4.8500

  ✓    9/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.60s  wall   1.36s  ETA   1.06s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.36s  wall   1.37s  ETA   0.82s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2hi_Valo_Iahi           job   0.49s  wall   1.39s  ETA   0.63s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.61s  wall   1.39s  ETA   0.46s  Vout=5.1499

  ✓   13/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.55s  wall   1.40s  ETA   0.32s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Valo_Ialo           job   0.62s  wall   1.40s  ETA   0.20s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2lo_Valo_Iahi           job   0.92s  wall   1.41s  ETA   0.09s  Vout=4.8500

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.51s  wall   1.41s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.54s  cpu=8.42s  speedup=5.46× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.02s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.03s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.09s  run R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.10s  run R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Vahi_… 0.02s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.15s  run R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Valo_… 0.12s, R1lo_R2lo_Vahi_… 0.07s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.20s  run R1lo_R2lo_Valo_… 0.18s, R1lo_R2lo_Valo_… 0.17s, R1lo_R2lo_Vahi_… 0.11s +3
  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.22s  run R1lo_R2lo_Valo_… 0.19s, R1lo_R2lo_Valo_… 0.18s, R1lo_R2lo_Vahi_… 0.13s +4
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.24s  run R1lo_R2lo_Valo_… 0.20s, R1lo_R2lo_Vahi_… 0.15s, R1lo_R2lo_Vahi_… 0.13s +4

  ✓    1/16  OK    R1lo_R2lo_Valo_Ialo           job   0.20s  wall   0.29s  ETA   4.29s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Ialo           t+  0.31s  run R1lo_R2lo_Valo_… 0.27s, R1lo_R2lo_Vahi_… 0.22s, R1lo_R2lo_Vahi_… 0.20s +5
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.32s  run R1lo_R2lo_Vahi_… 0.24s, R1lo_R2lo_Vahi_… 0.22s, R1lo_R2hi_Valo_… 0.17s +5

  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.40s  run R1lo_R2lo_Vahi_… 0.29s, R1lo_R2hi_Valo_… 0.24s, R1lo_R2hi_Valo_… 0.20s +5

  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.29s  wall   0.46s  ETA   3.20s  Vout=4.8500
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.48s  run R1lo_R2lo_Vahi_… 0.38s, R1lo_R2hi_Valo_… 0.33s, R1lo_R2hi_Valo_… 0.28s +5
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.53s  run R1lo_R2hi_Valo_… 0.38s, R1lo_R2hi_Valo_… 0.33s, R1lo_R2hi_Vahi_… 0.30s +5
  →  start  R1hi_R2hi_Valo_Iahi           t+  0.54s  run R1lo_R2hi_Valo_… 0.38s, R1lo_R2hi_Valo_… 0.34s, R1hi_R2lo_Valo_… 0.23s +5

  ✓    3/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.31s  wall   0.55s  ETA   2.40s  Vout=5.1499
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.61s  run R1lo_R2hi_Valo_… 0.46s, R1hi_R2lo_Valo_… 0.31s, R1hi_R2lo_Valo_… 0.29s +5

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.73s  run R1lo_R2hi_Valo_… 0.57s, R1hi_R2lo_Valo_… 0.40s, R1hi_R2lo_Vahi_… 0.33s +5

  ✓    4/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.27s  wall   0.79s  ETA   2.36s  Vout=5.1499

  ✓    5/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.43s  wall   0.94s  ETA   2.07s  Vout=5.1499

  ✓    6/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.30s  wall   1.00s  ETA   1.67s  Vout=5.1499

  ✓    7/16  OK    R1lo_R2hi_Valo_Iahi           job   0.41s  wall   1.01s  ETA   1.29s  Vout=4.8500

  ✓    8/16  OK    R1hi_R2lo_Valo_Ialo           job   0.42s  wall   1.01s  ETA   1.01s  Vout=4.8500

  ✓    9/16  OK    R1lo_R2hi_Valo_Ialo           job   0.58s  wall   1.01s  ETA   0.79s  Vout=4.8500

  ✓   10/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.40s  wall   1.01s  ETA   0.61s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2hi_Valo_Ialo           job   0.28s  wall   1.01s  ETA   0.46s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.43s  wall   1.02s  ETA   0.34s  Vout=5.1499

  ✓   13/16  OK    R1hi_R2lo_Valo_Iahi           job   0.64s  wall   1.02s  ETA   0.24s  Vout=4.8500

  ✓   14/16  OK    R1hi_R2hi_Valo_Iahi           job   0.46s  wall   1.04s  ETA   0.15s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.28s  wall   1.05s  ETA   0.07s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.39s  wall   1.06s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.09s  cpu=6.09s  speedup=5.59× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Vahi_… 0.00s
  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Vahi_… 0.00s +1

  →  start  R1lo_R2hi_Valo_Ialo           t+  0.02s  run R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.01s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.02s  run R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.01s +3

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.04s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Vahi_… 0.03s +4
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.04s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Vahi_… 0.03s +5
  →  start  R1hi_R2lo_Valo_Ialo           t+  0.07s  run R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.06s, R1lo_R2lo_Vahi_… 0.06s +5
  ✓    1/16  OK    R1lo_R2lo_Valo_Ialo           job   0.06s  wall   0.08s  ETA   1.20s  Vout=4.8500

  →  start  R1hi_R2lo_Valo_Iahi           t+  0.20s  run R1lo_R2lo_Vahi_… 0.19s, R1lo_R2lo_Vahi_… 0.19s, R1lo_R2hi_Valo_… 0.18s +5

  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.19s  wall   0.21s  ETA   1.47s  Vout=4.8500
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.25s  run R1lo_R2lo_Vahi_… 0.24s, R1lo_R2lo_Vahi_… 0.24s, R1lo_R2hi_Valo_… 0.23s +5
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.26s  run R1lo_R2lo_Vahi_… 0.25s, R1lo_R2lo_Vahi_… 0.25s, R1lo_R2hi_Valo_… 0.24s +5
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.27s  run R1lo_R2lo_Vahi_… 0.27s, R1lo_R2lo_Vahi_… 0.27s, R1lo_R2hi_Vahi_… 0.24s +5

  ✓    3/16  OK    R1lo_R2hi_Valo_Ialo           job   0.23s  wall   0.28s  ETA   1.21s  Vout=4.8500
  →  start  R1hi_R2hi_Valo_Iahi           t+  0.34s  run R1lo_R2lo_Vahi_… 0.33s, R1lo_R2hi_Vahi_… 0.31s, R1lo_R2hi_Vahi_… 0.30s +5

  ✓    4/16  OK    R1hi_R2lo_Valo_Ialo           job   0.19s  wall   0.42s  ETA   1.25s  Vout=4.8500
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.45s  run R1lo_R2lo_Vahi_… 0.44s, R1lo_R2hi_Vahi_… 0.41s, R1hi_R2lo_Valo_… 0.25s +5
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.45s  run R1lo_R2lo_Vahi_… 0.44s, R1hi_R2lo_Valo_… 0.25s, R1hi_R2lo_Vahi_… 0.20s +5

  ✓    5/16  OK    R1lo_R2hi_Valo_Iahi           job   0.25s  wall   0.48s  ETA   1.06s  Vout=4.8500

  ✓    6/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.33s  wall   0.53s  ETA   0.89s  Vout=5.1499

  ✓    7/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.41s  wall   0.61s  ETA   0.79s  Vout=5.1499

  ✓    8/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.41s  wall   0.63s  ETA   0.63s  Vout=5.1499

  ✓    9/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.19s  wall   0.64s  ETA   0.49s  Vout=5.1499

  ✓   10/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.44s  wall   0.65s  ETA   0.39s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2hi_Valo_Ialo           job   0.19s  wall   0.65s  ETA   0.30s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2lo_Valo_Iahi           job   0.29s  wall   0.67s  ETA   0.22s  Vout=4.8500

  ✓   13/16  OK    R1hi_R2hi_Valo_Iahi           job   0.21s  wall   0.69s  ETA   0.16s  Vout=4.8500

  ✓   14/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.33s  wall   0.70s  ETA   0.10s  Vout=5.1499

  ✓   15/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.22s  wall   0.70s  ETA   0.05s  Vout=5.1499

  ✓   16/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.25s  wall   0.70s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=0.70s  cpu=4.21s  speedup=5.99× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.00s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.01s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.03s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Vahi_… 0.00s
  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.08s  run R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Vahi_… 0.05s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.11s  run R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Valo_… 0.11s, R1lo_R2lo_Vahi_… 0.08s +2
  →  start  R1lo_R2hi_Valo_Iahi           t+  0.13s  run R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Vahi_… 0.10s, R1lo_R2lo_Vahi_… 0.05s +2

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.33s  run R1lo_R2lo_Vahi_… 0.29s, R1lo_R2lo_Vahi_… 0.25s, R1lo_R2hi_Valo_… 0.22s +2
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.33s  run R1lo_R2lo_Vahi_… 0.30s, R1lo_R2lo_Vahi_… 0.25s, R1lo_R2hi_Valo_… 0.22s +3

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.40s  run R1lo_R2lo_Vahi_… 0.37s, R1lo_R2lo_Vahi_… 0.32s, R1lo_R2hi_Valo_… 0.29s +3

  ✓    1/16  OK    R1lo_R2hi_Valo_Iahi           job   0.24s  wall   0.41s  ETA   6.12s  Vout=4.8500

  →  start  R1hi_R2lo_Valo_Iahi           t+  0.44s  run R1lo_R2lo_Vahi_… 0.41s, R1lo_R2hi_Valo_… 0.33s, R1lo_R2hi_Vahi_… 0.12s +3

  ✓    2/16  OK    R1lo_R2lo_Valo_Iahi           job   0.21s  wall   0.49s  ETA   3.42s  Vout=4.8500

  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.54s  run R1lo_R2lo_Vahi_… 0.51s, R1lo_R2hi_Vahi_… 0.21s, R1lo_R2hi_Vahi_… 0.20s +3  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.54s  run R1lo_R2lo_Vahi_… 0.51s, R1lo_R2hi_Vahi_… 0.22s, R1lo_R2hi_Vahi_… 0.21s +4
  ✓    3/16  OK    R1lo_R2lo_Valo_Ialo           job   0.13s  wall   0.57s  ETA   2.48s  Vout=4.8500
  →  start  R1hi_R2hi_Valo_Ialo           t+  0.58s  run R1lo_R2lo_Vahi_… 0.54s, R1lo_R2hi_Vahi_… 0.25s, R1lo_R2hi_Vahi_… 0.24s +5

  ✓    4/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.37s  wall   0.66s  ETA   1.99s  Vout=5.1499
  →  start  R1hi_R2hi_Valo_Iahi           t+  0.68s  run R1lo_R2lo_Vahi_… 0.65s, R1lo_R2hi_Vahi_… 0.35s, R1hi_R2lo_Valo_… 0.28s +5

  ✓    5/16  OK    R1lo_R2hi_Valo_Ialo           job   0.43s  wall   0.74s  ETA   1.63s  Vout=4.8500
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.81s  run R1lo_R2hi_Vahi_… 0.48s, R1hi_R2lo_Valo_… 0.41s, R1hi_R2lo_Valo_… 0.37s +5
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.81s  run R1lo_R2hi_Vahi_… 0.49s, R1hi_R2lo_Valo_… 0.41s, R1hi_R2lo_Valo_… 0.37s +5

  ✓    6/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.35s  wall   0.84s  ETA   1.41s  Vout=5.1499

  ✓    7/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.78s  wall   0.95s  ETA   1.23s  Vout=5.1499

  …  7/16 done  ok=7 fail=0  wall 1.00s  ETA 1.29s  run R1lo_R2hi_Vahi_… 0.68s, R1hi_R2lo_Valo_… 0.60s, R1hi_R2lo_Valo_… 0.56s +3
  ✓    8/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.27s  wall   1.03s  ETA   1.03s  Vout=5.1499

  ✓    9/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.32s  wall   1.06s  ETA   0.82s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.17s  wall   1.13s  ETA   0.68s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2lo_Valo_Iahi           job   0.58s  wall   1.13s  ETA   0.52s  Vout=4.8500

  ✓   12/16  OK    R1hi_R2hi_Valo_Iahi           job   0.35s  wall   1.14s  ETA   0.38s  Vout=4.8500

  ✓   13/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.74s  wall   1.14s  ETA   0.26s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2lo_Valo_Ialo           job   0.69s  wall   1.14s  ETA   0.16s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2hi_Valo_Ialo           job   0.51s  wall   1.14s  ETA   0.08s  Vout=4.8500

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.33s  wall   1.14s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.15s  cpu=6.45s  speedup=5.61× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.02s  run R1lo_R2lo_Valo_… 0.00s
  →  start  R1lo_R2lo_Valo_Iahi           t+  0.03s  run R1lo_R2lo_Valo_… 0.02s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.04s  run R1lo_R2lo_Valo_… 0.03s, R1lo_R2lo_Valo_… 0.01s, R1lo_R2lo_Vahi_… 0.00s

  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.09s  run R1lo_R2lo_Valo_… 0.08s, R1lo_R2lo_Valo_… 0.06s, R1lo_R2lo_Vahi_… 0.05s +1

  →  start  R1lo_R2hi_Valo_Ialo           t+  0.11s  run R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Valo_… 0.07s, R1lo_R2lo_Vahi_… 0.06s +2
  →  start  R1lo_R2hi_Valo_Iahi           t+  0.15s  run R1lo_R2lo_Valo_… 0.14s, R1lo_R2lo_Valo_… 0.12s, R1lo_R2lo_Vahi_… 0.11s +3

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.22s  run R1lo_R2lo_Valo_… 0.18s, R1lo_R2lo_Vahi_… 0.17s, R1lo_R2lo_Vahi_… 0.12s +3
  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.25s  run R1lo_R2lo_Valo_… 0.21s, R1lo_R2lo_Vahi_… 0.20s, R1lo_R2lo_Vahi_… 0.15s +4

  →  start  R1hi_R2lo_Valo_Ialo           t+  0.38s  run R1lo_R2lo_Valo_… 0.35s, R1lo_R2lo_Vahi_… 0.34s, R1lo_R2hi_Valo_… 0.27s +4
  ✓    1/16  OK    R1lo_R2lo_Valo_Ialo           job   0.15s  wall   0.44s  ETA   6.67s  Vout=4.8500
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.46s  run R1lo_R2lo_Valo_… 0.42s, R1lo_R2lo_Vahi_… 0.41s, R1lo_R2hi_Valo_… 0.35s +5
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.47s  run R1lo_R2lo_Vahi_… 0.42s, R1lo_R2hi_Valo_… 0.36s, R1lo_R2hi_Valo_… 0.32s +5
  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.47s  run R1lo_R2hi_Valo_… 0.37s, R1lo_R2hi_Valo_… 0.33s, R1lo_R2hi_Vahi_… 0.26s +5

  →  start  R1hi_R2hi_Valo_Ialo           t+  0.56s  run R1lo_R2hi_Valo_… 0.46s, R1lo_R2hi_Vahi_… 0.35s, R1lo_R2hi_Vahi_… 0.32s +5
  ✓    2/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.29s  wall   0.59s  ETA   4.16s  Vout=5.1499

  ✓    3/16  OK    R1lo_R2lo_Valo_Iahi           job   0.43s  wall   0.60s  ETA   2.59s  Vout=4.8500

  →  start  R1hi_R2hi_Valo_Iahi           t+  0.63s  run R1lo_R2hi_Vahi_… 0.41s, R1lo_R2hi_Vahi_… 0.38s, R1hi_R2lo_Valo_… 0.25s +5
  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.72s  run R1lo_R2hi_Vahi_… 0.50s, R1lo_R2hi_Vahi_… 0.47s, R1hi_R2lo_Valo_… 0.26s +5
  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.80s  run R1lo_R2hi_Vahi_… 0.59s, R1lo_R2hi_Vahi_… 0.56s, R1hi_R2lo_Valo_… 0.35s +5
  ✓    4/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.43s  wall   0.82s  ETA   2.45s  Vout=5.1499

  ✓    5/16  OK    R1lo_R2hi_Valo_Iahi           job   0.41s  wall   1.01s  ETA   2.23s  Vout=4.8500

  …  5/16 done  ok=5 fail=0  wall 1.03s  ETA 2.26s  run R1lo_R2hi_Vahi_… 0.81s, R1lo_R2hi_Vahi_… 0.78s, R1hi_R2hi_Valo_… 0.46s +2

  ✓    6/16  OK    R1lo_R2hi_Valo_Ialo           job   0.52s  wall   1.04s  ETA   1.74s  Vout=4.8500

  ✓    7/16  OK    R1hi_R2lo_Valo_Ialo           job   0.34s  wall   1.05s  ETA   1.36s  Vout=4.8500

  ✓    8/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.34s  wall   1.10s  ETA   1.10s  Vout=5.1499

  ✓    9/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.53s  wall   1.11s  ETA   0.86s  Vout=5.1499

  ✓   10/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.29s  wall   1.11s  ETA   0.66s  Vout=5.1499

  ✓   11/16  OK    R1hi_R2lo_Valo_Iahi           job   0.56s  wall   1.11s  ETA   0.50s  Vout=4.8500

  ✓   12/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.80s  wall   1.11s  ETA   0.37s  Vout=5.1499

  ✓   13/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.86s  wall   1.11s  ETA   0.26s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Valo_Ialo           job   0.51s  wall   1.12s  ETA   0.16s  Vout=4.8500

  ✓   15/16  OK    R1hi_R2hi_Valo_Iahi           job   0.47s  wall   1.13s  ETA   0.08s  Vout=4.8500

  ✓   16/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.33s  wall   1.16s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.19s  cpu=7.25s  speedup=6.10× vs serial

------------------------------------------------------------------------------

------------------------------------------------------------------------------

  ngspice WC hypercube

  ngspice  jobs=16  workers=8  requested=auto  cpu=8  env P5V_SPICE_WORKERS=''

  queue: R1lo_R2lo_Valo_Ialo, R1lo_R2lo_Valo_Iahi, R1lo_R2lo_Vahi_Ialo, R1lo_R2lo_Vahi_Iahi, R1lo_R2hi_Valo_Ialo, R1lo_R2hi_Valo_Iahi  +10 more

------------------------------------------------------------------------------

  →  start  R1lo_R2lo_Valo_Ialo           t+  0.02s  run R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Valo_Iahi           t+  0.03s  run R1lo_R2lo_Valo_… 0.00s, R1lo_R2lo_Valo_… 0.00s

  →  start  R1lo_R2lo_Vahi_Ialo           t+  0.07s  run R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Valo_… 0.05s, R1lo_R2lo_Vahi_… 0.00s
  →  start  R1lo_R2lo_Vahi_Iahi           t+  0.12s  run R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Valo_… 0.09s, R1lo_R2lo_Vahi_… 0.04s +1
  →  start  R1lo_R2hi_Valo_Ialo           t+  0.15s  run R1lo_R2lo_Valo_… 0.13s, R1lo_R2lo_Valo_… 0.12s, R1lo_R2lo_Vahi_… 0.08s +2

  →  start  R1lo_R2hi_Valo_Iahi           t+  0.18s  run R1lo_R2lo_Valo_… 0.16s, R1lo_R2lo_Valo_… 0.15s, R1lo_R2lo_Vahi_… 0.11s +3

  →  start  R1lo_R2hi_Vahi_Ialo           t+  0.41s  run R1lo_R2lo_Valo_… 0.38s, R1lo_R2lo_Valo_… 0.38s, R1lo_R2lo_Vahi_… 0.33s +4

  →  start  R1lo_R2hi_Vahi_Iahi           t+  0.50s  run R1lo_R2lo_Valo_… 0.48s, R1lo_R2lo_Vahi_… 0.38s, R1lo_R2hi_Valo_… 0.35s +3
  →  start  R1hi_R2lo_Valo_Ialo           t+  0.51s  run R1lo_R2lo_Valo_… 0.48s, R1lo_R2lo_Vahi_… 0.39s, R1lo_R2hi_Valo_… 0.36s +4
  →  start  R1hi_R2lo_Valo_Iahi           t+  0.53s  run R1lo_R2lo_Valo_… 0.51s, R1lo_R2lo_Vahi_… 0.41s, R1lo_R2hi_Valo_… 0.35s +4

  ✓    1/16  OK    R1lo_R2hi_Valo_Ialo           job   0.38s  wall   0.56s  ETA   8.39s  Vout=4.8500
  →  start  R1hi_R2lo_Vahi_Ialo           t+  0.58s  run R1lo_R2lo_Valo_… 0.56s, R1lo_R2lo_Vahi_… 0.46s, R1lo_R2hi_Valo_… 0.40s +5

  ✓    2/16  OK    R1lo_R2lo_Vahi_Ialo           job   0.38s  wall   0.69s  ETA   4.86s  Vout=5.1499

  ✓    3/16  OK    R1lo_R2lo_Valo_Iahi           job   0.44s  wall   0.78s  ETA   3.40s  Vout=4.8500

  →  start  R1hi_R2lo_Vahi_Iahi           t+  0.83s  run R1lo_R2lo_Valo_… 0.81s, R1lo_R2lo_Vahi_… 0.71s, R1lo_R2hi_Vahi_… 0.42s +5

  →  start  R1hi_R2hi_Valo_Ialo           t+  0.87s  run R1lo_R2lo_Valo_… 0.85s, R1lo_R2hi_Vahi_… 0.47s, R1lo_R2hi_Vahi_… 0.38s +5
  →  start  R1hi_R2hi_Valo_Iahi           t+  0.88s  run R1lo_R2lo_Valo_… 0.85s, R1lo_R2hi_Vahi_… 0.47s, R1hi_R2lo_Valo_… 0.37s +5
  ✓    4/16  OK    R1lo_R2hi_Valo_Iahi           job   0.65s  wall   0.88s  ETA   2.64s  Vout=4.8500

  →  start  R1hi_R2hi_Vahi_Ialo           t+  0.91s  run R1lo_R2lo_Valo_… 0.89s, R1lo_R2hi_Vahi_… 0.51s, R1hi_R2lo_Valo_… 0.38s +5

  →  start  R1hi_R2hi_Vahi_Iahi           t+  0.98s  run R1lo_R2lo_Valo_… 0.96s, R1lo_R2hi_Vahi_… 0.57s, R1hi_R2lo_Vahi_… 0.40s +5

  …  4/16 done  ok=4 fail=0  wall 1.02s  ETA 3.05s  run R1lo_R2lo_Valo_… 0.99s, R1hi_R2lo_Vahi_… 0.44s, R1hi_R2lo_Vahi_… 0.19s +4

  ✓    5/16  OK    R1lo_R2lo_Vahi_Iahi           job   0.76s  wall   1.03s  ETA   2.27s  Vout=5.1499

  ✓    6/16  OK    R1lo_R2hi_Vahi_Iahi           job   0.38s  wall   1.12s  ETA   1.87s  Vout=5.1499

  ✓    7/16  OK    R1hi_R2lo_Valo_Ialo           job   0.41s  wall   1.28s  ETA   1.65s  Vout=4.8500

  ✓    8/16  OK    R1hi_R2lo_Valo_Iahi           job   0.45s  wall   1.29s  ETA   1.29s  Vout=4.8500

  ✓    9/16  OK    R1lo_R2hi_Vahi_Ialo           job   0.58s  wall   1.29s  ETA   1.00s  Vout=5.1499

  ✓   10/16  OK    R1lo_R2lo_Valo_Ialo           job   1.00s  wall   1.29s  ETA   0.77s  Vout=4.8500

  ✓   11/16  OK    R1hi_R2lo_Vahi_Ialo           job   0.64s  wall   1.31s  ETA   0.60s  Vout=5.1499

  ✓   12/16  OK    R1hi_R2hi_Valo_Ialo           job   0.37s  wall   1.31s  ETA   0.44s  Vout=4.8500

  ✓   13/16  OK    R1hi_R2hi_Vahi_Iahi           job   0.27s  wall   1.33s  ETA   0.31s  Vout=5.1499

  ✓   14/16  OK    R1hi_R2hi_Vahi_Ialo           job   0.37s  wall   1.34s  ETA   0.19s  Vout=5.1499

  ✓   15/16  OK    R1hi_R2hi_Valo_Iahi           job   0.42s  wall   1.35s  ETA   0.09s  Vout=4.8500

  ✓   16/16  OK    R1hi_R2lo_Vahi_Iahi           job   0.49s  wall   1.37s  ETA   0.00s  Vout=5.1499

------------------------------------------------------------------------------

  [ngspice WC hypercube] done  16 ok / 0 fail / 16 jobs  workers=8  wall=1.47s  cpu=7.98s  speedup=5.45× vs serial

------------------------------------------------------------------------------

    temp_c  vout_nom   vout_lo   vout_hi  n_corners   engine
0    -40.0  4.976872  4.849951  5.149948         16  ngspice
1    -20.0  4.988632  4.849951  5.149948         16  ngspice
2      0.0  4.998040  4.849951  5.149948         16  ngspice
3     20.0  4.999608  4.849951  5.149948         16  ngspice
4     25.0  5.000000  4.924951  5.074949         16  ngspice
5     40.0  5.001176  4.849951  5.149948         16  ngspice
6     60.0  4.998824  4.849951  5.149948         16  ngspice
7     80.0  4.992552  4.849951  5.149948         16  ngspice
8     85.0  4.990984  4.849951  5.149948         16  ngspice
9    100.0  4.986280  4.849951  5.149948         16  ngspice
10   120.0  4.980008  4.849951  5.149948         16  ngspice
11   125.0  4.978440  4.849951  5.149948         16  ngspice

LTspice helper is not in this repository. Vendor LT3010.lib is not redistributed.
LTspice temp batch skipped (RUN_LTSPICE_BATCH=False). Existing logs still parsed.

   temp_c  vout   engine
0   -40.0   NaN  LTspice
1    25.0   NaN  LTspice
2   125.0   NaN  LTspice

   temp_c   engine  vout_lo  vout_hi  n_corners
0   -40.0  LTspice      NaN      NaN          0
1    25.0  LTspice      NaN      NaN          0
2   125.0  LTspice      NaN      NaN          0

cell:84: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

     T_C    an_nom  an_lo  an_hi    ng_nom     ng_lo     ng_hi  ng-an_mV
0  -40.0  4.976872  4.850  5.150  4.976822  4.849951  5.149948 -0.049815
1   25.0  5.000000  4.925  5.075  4.999950  4.924951  5.074949 -0.050000
2  125.0  4.978440  4.850  5.150  4.978390  4.849951  5.149948 -0.049828

## Dropout, $I_{\mathrm{GND}}$, dissipation, $T_j$, PSRR vs $T$

In [4]:
fig, ax = plt.subplots(figsize=(8.0, 4.0))
ax.plot(sw.frame.temp_c, 1e3*sw.frame.vdo_typ, "k-", lw=1.7, label="Vdo typ")
ax.plot(sw.frame.temp_c, 1e3*sw.frame.vdo_wc, "C3--", lw=1.3, label="Vdo max over temp")
ax.set_xlabel("T (°C)")
ax.set_ylabel("dropout (mV)")
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)
plots.apply_annotations(ax, [dict(text="50 mA", xy=(25, 1e3*sw.frame.vdo_typ.iloc[len(sw.frame)//2]), offset=(10, 10), arrow=True)])
plots.savefig(fig, FIG/"06_vdo_vs_t.png")
plt.show()
ann_g = [dict(text="25 °C", xy=(25, float(sw.frame.loc[np.isclose(sw.frame.temp_c, 25), "vout"].iloc[0])), offset=(10, 12), arrow=True)]
plots.plot_temp_grid(sw.frame, annotations=ann_g, path=FIG/"06_temp_grid.png")
plt.show()
fig, ax = plt.subplots(figsize=(8.0, 3.8))
ax.plot(sw.frame.temp_c, 1e3*sw.frame.ignd_typ, "k-", lw=1.7, label="typ")
ax.plot(sw.frame.temp_c, 1e3*sw.frame.ignd_max, "C3--", lw=1.3, label="max")
ax.set_xlabel("T (°C)"); ax.set_ylabel("Ignd (mA)"); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)
plots.savefig(fig, FIG/"06_ignd_vs_t.png"); plt.show()
fig, ax = plt.subplots(figsize=(8.0, 3.8))
ax.plot(sw.frame.temp_c, 1e3*sw.frame.p_diss, "k-", lw=1.7)
ax.set_xlabel("T (°C)"); ax.set_ylabel("Pdiss (mW)")
ax.set_title("LDO dissipation vs T (typ Ignd)")
ax.grid(True, alpha=0.3)
plots.savefig(fig, FIG/"06_pdiss_vs_t.png"); plt.show()
fig, ax = plt.subplots(figsize=(8.0, 3.8))
ax.plot(sw.frame.temp_c, sw.frame.tj_c, "k-", lw=1.7, label="Tj")
ax.axhline(p.ldo.tj_max_c, color="C3", ls="--", label="Tjmax")
ax.set_xlabel("T (°C)"); ax.set_ylabel("°C"); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)
ax.set_title("Junction temperature vs ambient")
plots.savefig(fig, FIG/"06_tj_vs_t.png"); plt.show()
# PSRR min over-temp is datasheet typ−10 dB (page 3)
f = np.logspace(1, 6, 241)
fig, ax = plt.subplots(figsize=(8.2, 4.4))
ax.semilogx(f, psrr_db(f, cout=p.cout), "k-", lw=1.8, label="typ 25 °C (G21)")
ax.semilogx(f, psrr_db(f, cout=p.cout, typ=False), "C3--", lw=1.4, label="min (over temp class)")
ax.axvline(120, color="0.5", ls=":", lw=0.9)
ax.set_xlabel("f (Hz)"); ax.set_ylabel("PSRR (dB)")
ax.set_title("PSRR  25 °C typ vs min (over-temp class)")
ax.legend(fontsize=8); ax.grid(True, which="both", alpha=0.3)
plots.savefig(fig, FIG/"06_psrr_vs_t.png"); plt.show()

cell:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

cell:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
cell:18: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plots.savefig(fig, FIG/"06_ignd_vs_t.png"); plt.show()

cell:24: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plots.savefig(fig, FIG/"06_pdiss_vs_t.png"); plt.show()
cell:30: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plots.savefig(fig, FIG/"06_tj_vs_t.png"); plt.show()

cell:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plots.savefig(fig, FIG/"06_psrr_vs_t.png"); plt.show()